import type { Store } from "./types";

function ago(hours: number, minutes = 0): string {
  return new Date(Date.now() - (hours * 3600 + minutes * 60) * 1000).toISOString();
}

export function createSeed(): Store {
  return {
    agents: [
      {
        id: "AGT-1",
        name: "Elena Vargas",
        role: "Agente L2 · Soporte intermedio",
        extension: "204",
        email: "elena.vargas@opencall.local",
        status: "disponible",
      },
      {
        id: "AGT-2",
        name: "Mesa L3 · Especialistas",
        role: "Escalado técnico",
        extension: "300",
        email: "l3@opencall.local",
        status: "disponible",
      },
    ],
    customers: [
      {
        id: "CUS-101",
        name: "Marta López",
        company: "NorteLogística",
        phone: "+57 300 415 8821",
        email: "marta.lopez@nortelogistica.co",
        plan: "Pro",
        accountId: "NL-88421",
        notes: "Contacto principal de operaciones. Prefiere confirmación por correo al cerrar.",
        createdAt: ago(400),
      },
      {
        id: "CUS-102",
        name: "Carlos Méndez",
        company: "Clínica Sur",
        phone: "+57 310 220 1190",
        email: "carlos.mendez@clinicasur.co",
        plan: "Enterprise",
        accountId: "CS-10290",
        notes: "Cuenta sensible: incidencias de acceso se tratan como alta prioridad.",
        createdAt: ago(520),
      },
      {
        id: "CUS-103",
        name: "Ana Beltrán",
        company: "RetailAndes",
        phone: "+57 315 908 3344",
        email: "ana.beltran@retailandes.com",
        plan: "Pro",
        accountId: "RA-55210",
        notes: "Suele llamar por facturación al cierre de mes.",
        createdAt: ago(210),
      },
      {
        id: "CUS-104",
        name: "Julián Torres",
        company: "Andes Freight",
        phone: "+57 301 667 4412",
        email: "julian.torres@andesfreight.io",
        plan: "Starter",
        accountId: "AF-19002",
        notes: "Nuevo en la plataforma. Guiar con paciencia y ofrecer resumen.",
        createdAt: ago(40),
      },
      {
        id: "CUS-105",
        name: "Lucía Romero",
        company: "Costa Digital",
        phone: "+57 304 118 7755",
        email: "lucia.romero@costadigital.co",
        plan: "Enterprise",
        accountId: "CD-33001",
        notes: "Integraciones CRM propias. No duplicar tickets si ya existe uno abierto.",
        createdAt: ago(800),
      },
    ],
    tickets: [
      {
        id: "TKT-1041",
        customerId: "CUS-101",
        callId: "CALL-9001",
        subject: "No puede restablecer la contraseña del portal",
        description:
          "Marta indica que el enlace de recuperación caduca al instante. Ya validó el correo de la cuenta.",
        category: "acceso",
        priority: "media",
        status: "resuelto",
        channel: "telefono",
        assignee: "Elena Vargas",
        escalated: false,
        tags: ["contraseña", "portal"],
        createdAt: ago(5, 20),
        updatedAt: ago(5, 5),
        firstResponseAt: ago(5, 18),
        resolvedAt: ago(5, 5),
        crmSync: { status: "nativo", lastEvent: "ticket.resolved" },
        events: [
          {
            at: ago(5, 20),
            actor: "Elena Vargas",
            type: "creado",
            message: "Ticket abierto durante la llamada.",
          },
          {
            at: ago(5, 5),
            actor: "Elena Vargas",
            type: "resuelto",
            message: "Se reenvió el enlace de recuperación y se confirmó el acceso.",
          },
        ],
      },
      {
        id: "TKT-1042",
        customerId: "CUS-102",
        subject: "Error 503 al sincronizar historias clínicas",
        description:
          "Sincronización intermitente desde las 07:10. Afecta a 12 usuarios del turno mañana.",
        category: "incidencia",
        priority: "alta",
        status: "escalado",
        channel: "telefono",
        assignee: "Elena Vargas",
        escalated: true,
        tags: ["sincronización", "503"],
        createdAt: ago(2, 10),
        updatedAt: ago(1, 40),
        firstResponseAt: ago(2, 8),
        crmSync: { status: "enviado", externalId: "CRM-8821", lastEvent: "ticket.escalated" },
        escalation: {
          protocolId: "PRT-L2",
          destination: "L3 · Plataforma",
          reason: "Error 503 persistente tras reinicio de sesión y comprobación de estado del servicio.",
          checklist: [
            "Identidad verificada",
            "FAQ y manual consultados",
            "Intento de resolución L2 documentado",
            "Impacto y severidad informados al usuario",
          ],
          at: ago(1, 40),
        },
        events: [
          {
            at: ago(2, 10),
            actor: "Elena Vargas",
            type: "creado",
            message: "Filtrado inicial: incidencia de plataforma con impacto en turno.",
          },
          {
            at: ago(1, 40),
            actor: "Elena Vargas",
            type: "escalado",
            message: "Escalado a L3 · Plataforma según matriz de criticidad.",
          },
        ],
      },
      {
        id: "TKT-1043",
        customerId: "CUS-103",
        subject: "Duda sobre cargo duplicado en la factura de agosto",
        description: "Aparece un cargo Pro y un cargo extra de usuarios. Quiere desglose.",
        category: "facturacion",
        priority: "media",
        status: "en_progreso",
        channel: "telefono",
        assignee: "Elena Vargas",
        escalated: false,
        tags: ["factura", "agosto"],
        createdAt: ago(1, 5),
        updatedAt: ago(0, 50),
        firstResponseAt: ago(1, 3),
        crmSync: { status: "nativo", lastEvent: "ticket.updated" },
        events: [
          {
            at: ago(1, 5),
            actor: "Elena Vargas",
            type: "creado",
            message: "Consulta de facturación. Se está revisando el desglose del plan.",
          },
        ],
      },
      {
        id: "TKT-1044",
        customerId: "CUS-104",
        subject: "Cómo invitar a un segundo usuario al espacio de trabajo",
        description: "Cliente nuevo. No encuentra el menú de invitaciones.",
        category: "consulta",
        priority: "baja",
        status: "nuevo",
        channel: "manual",
        assignee: "Elena Vargas",
        escalated: false,
        tags: ["onboarding"],
        createdAt: ago(0, 25),
        updatedAt: ago(0, 25),
        crmSync: { status: "pendiente" },
        events: [
          {
            at: ago(0, 25),
            actor: "Sistema",
            type: "creado",
            message: "Ticket registrado para seguimiento proactivo.",
          },
        ],
      },
      {
        id: "TKT-1045",
        customerId: "CUS-105",
        subject: "Webhook del CRM del cliente no recibe actualizaciones",
        description:
          "Costa Digital reporta que su CRM dejó de recibir eventos ticket.updated desde ayer.",
        category: "producto",
        priority: "alta",
        status: "en_progreso",
        channel: "crm",
        assignee: "Elena Vargas",
        escalated: false,
        tags: ["crm", "integración"],
        createdAt: ago(8),
        updatedAt: ago(0, 90),
        firstResponseAt: ago(7, 50),
        crmSync: { status: "nativo", lastEvent: "ticket.created" },
        events: [
          {
            at: ago(8),
            actor: "Elena Vargas",
            type: "creado",
            message: "Se abre caso para revisar la bandeja de integración CRM.",
          },
          {
            at: ago(0, 90),
            actor: "Elena Vargas",
            type: "nota",
            message: "Pendiente de URL de webhook actualizada por el cliente.",
          },
        ],
      },
    ],
    calls: [
      {
        id: "CALL-9001",
        customerId: "CUS-101",
        ticketId: "TKT-1041",
        from: "+57 300 415 8821",
        to: "+57 601 555 0100",
        status: "finalizada",
        queuedAt: ago(5, 22),
        answeredAt: ago(5, 21),
        endedAt: ago(5, 4),
        agentId: "AGT-1",
        holdSeconds: 0,
        notes: "Contraseña resuelta en L2 con FAQ de recuperación.",
        wrapUp: {
          disposition: "resuelto_l2",
          proactiveActions: ["resumen_correo", "confirmar_acceso"],
          summary: "Se restableció el acceso y se envió un resumen del procedimiento.",
        },
      },
      {
        id: "CALL-9002",
        customerId: "CUS-102",
        ticketId: "TKT-1042",
        from: "+57 310 220 1190",
        to: "+57 601 555 0100",
        status: "finalizada",
        queuedAt: ago(2, 12),
        answeredAt: ago(2, 11),
        endedAt: ago(1, 38),
        agentId: "AGT-1",
        holdSeconds: 35,
        notes: "Filtrado inicial completado. Escalado a L3.",
        wrapUp: {
          disposition: "escalado",
          proactiveActions: ["callback_comprometido", "resumen_correo"],
          summary: "Se informó el protocolo, el tiempo estimado L3 y se dejó callback.",
        },
      },
      {
        id: "CALL-9003",
        customerId: "CUS-103",
        ticketId: "TKT-1043",
        from: "+57 315 908 3344",
        to: "+57 601 555 0100",
        status: "finalizada",
        queuedAt: ago(1, 8),
        answeredAt: ago(1, 7),
        endedAt: ago(0, 48),
        agentId: "AGT-1",
        holdSeconds: 0,
        notes: "Consulta de factura en curso; falta desglose de usuarios extra.",
        wrapUp: {
          disposition: "seguimiento",
          proactiveActions: ["seguimiento_programado"],
          summary: "Se revisará el desglose y se devolverá la llamada antes de las 16:00.",
        },
      },
    ],
    faqs: [
      {
        id: "FAQ-1",
        question: "¿Cómo restablecer la contraseña del portal?",
        answer:
          "Desde Iniciar sesión → ¿Olvidaste tu contraseña?. El enlace es válido 30 minutos. Si caduca al instante, comprobar que no haya redirección corporativa y reenviar el correo desde Usuarios → Seguridad. En L2 se puede forzar un enlace de un solo uso.",
        category: "acceso",
        keywords: ["contraseña", "password", "acceso", "login", "olvidé"],
        l2Resolvable: true,
      },
      {
        id: "FAQ-2",
        question: "¿Cómo invitar usuarios al espacio de trabajo?",
        answer:
          "Ajustes → Equipo → Invitar. Se necesita rol Administrador. El invitado recibe un correo; si no llega, revisar spam y reenviar desde el mismo panel. El plan Starter admite 3 usuarios.",
        category: "producto",
        keywords: ["invitar", "usuario", "equipo", "onboarding"],
        l2Resolvable: true,
      },
      {
        id: "FAQ-3",
        question: "¿Qué significa un cargo duplicado en la factura?",
        answer:
          "El cargo base del plan y el de usuarios adicionales se muestran por separado. No es un doble cobro si las líneas tienen conceptos distintos. Si ambas líneas dicen «Plan Pro», abrir incidencia de facturación y adjuntar el PDF.",
        category: "facturacion",
        keywords: ["factura", "cargo", "duplicado", "cobro"],
        l2Resolvable: true,
      },
      {
        id: "FAQ-4",
        question: "Error 503 o servicio no disponible",
        answer:
          "Comprobar status.opencall.local y pedir al usuario hora, navegador y si afecta a todo el equipo. Si el error persiste más de 10 minutos o impacta a varios usuarios, no insistir en L2: documentar y escalar a L3 · Plataforma.",
        category: "incidencia",
        keywords: ["503", "caída", "caida", "no funciona", "sincronizar", "sincronización"],
        l2Resolvable: false,
      },
      {
        id: "FAQ-5",
        question: "Horario de atención y tiempos de respuesta L2",
        answer:
          "Lunes a viernes, 07:00–19:00 (America/Bogota). Objetivo de primera respuesta: 45 segundos en llamada. Consultas resueltas en L2 se cierran en la misma conversación; las escaladas informan un SLA según la matriz.",
        category: "consulta",
        keywords: ["horario", "sla", "tiempo", "respuesta"],
        l2Resolvable: true,
      },
      {
        id: "FAQ-6",
        question: "¿Cómo se registra un ticket en el CRM?",
        answer:
          "Toda llamada atendida genera o actualiza un ticket. En modo nativo queda en OpenCall. Si el cliente tiene CRM propio, se envía ticket.created / updated / escalated al webhook configurado para no duplicar el caso en su sistema.",
        category: "producto",
        keywords: ["crm", "ticket", "integración", "webhook"],
        l2Resolvable: true,
      },
      {
        id: "FAQ-7",
        question: "Cambio de método de pago",
        answer:
          "Facturación → Método de pago. Solo el titular de la cuenta. L2 no ve números completos de tarjeta. Si el cobro fue rechazado, pedir que actualice el método y reintentar el pago pendiente.",
        category: "facturacion",
        keywords: ["pago", "tarjeta", "billing"],
        l2Resolvable: true,
      },
      {
        id: "FAQ-8",
        question: "La app móvil no sincroniza desde hace horas",
        answer:
          "Pedir versión de la app, sistema operativo y si el indicador de red aparece en rojo. Forzar cierre, reingreso y Wi-Fi. Si hay más de un dispositivo afectado o el panel web también falla, tratarlo como incidencia de plataforma.",
        category: "incidencia",
        keywords: ["móvil", "app", "sincroniza", "offline"],
        l2Resolvable: true,
      },
    ],
    manuals: [
      {
        id: "MAN-1",
        title: "Guía L2 · Filtrado inicial de incidencias",
        summary: "Plantilla operativa de OpenCall mientras el cliente entrega sus manuales de producto.",
        status: "activo",
        updatedAt: ago(12),
        sections: [
          {
            heading: "Qué cubre el nivel intermedio",
            body: "Dudas frecuentes, acceso, facturación estándar, configuración básica y diagnóstico de primer nivel. No incluye cambios de código, accesos de infraestructura ni excepciones contractuales.",
          },
          {
            heading: "Preguntas de filtrado",
            body: "1) ¿Quién llama y a qué cuenta pertenece? 2) ¿Cuántos usuarios están afectados? 3) ¿Desde cuándo? 4) ¿Hay un identificador de error? 5) ¿Ya se intentó el procedimiento FAQ?",
          },
        ],
      },
      {
        id: "MAN-2",
        title: "Manual de producto del cliente",
        summary: "Espacio reservado. El cliente cargará aquí los manuales definitivos de su producto.",
        status: "pendiente_cliente",
        updatedAt: ago(0, 1),
        sections: [
          {
            heading: "Pendiente",
            body: "Cuando el cliente facilite los manuales, se versionarán aquí y la consola los sugerirá automáticamente durante la llamada.",
          },
        ],
      },
    ],
    scripts: [
      {
        id: "SCR-1",
        name: "Apertura y verificación",
        scenario: "Toda llamada entrante",
        steps: [
          {
            id: "s1",
            title: "Saludo",
            text: "Buenos días, habla Elena de soporte intermedio. ¿Con quién tengo el gusto y en qué puedo ayudarle?",
          },
          {
            id: "s2",
            title: "Verificar identidad",
            text: "Para proteger la cuenta, ¿me confirma nombre, empresa y un dato de la cuenta (correo o ID)?",
          },
          {
            id: "s3",
            title: "Reformular",
            text: "Si entendí bien, el tema es [resumen]. ¿Es correcto? Así filtramos bien la incidencia desde el inicio.",
          },
          {
            id: "s4",
            title: "Compromiso de tiempo",
            text: "Voy a revisarlo ahora con usted. Si es algo que resolvemos en este nivel, lo dejamos cerrado hoy; si hay que escalar, le explico el siguiente paso y el tiempo estimado.",
            proactive: true,
          },
        ],
      },
      {
        id: "SCR-2",
        name: "Recuperación de acceso",
        scenario: "Contraseña, bloqueo o enlace caducado",
        steps: [
          {
            id: "s1",
            title: "Confirmar canal",
            text: "¿El correo de recuperación llega a [email de la ficha]? Si no, no reenviamos a otra bandeja sin verificación.",
          },
          {
            id: "s2",
            title: "Procedimiento L2",
            text: "Reenviar enlace de un solo uso y esperar en línea a que ingrese. No pedir la contraseña nueva.",
          },
          {
            id: "s3",
            title: "Cierre proactivo",
            text: "Le envío un resumen con el procedimiento por si vuelve a ocurrir, y dejo el ticket en el CRM para trazabilidad.",
            proactive: true,
          },
        ],
      },
      {
        id: "SCR-3",
        name: "Escalado a un nivel superior",
        scenario: "Cuando el protocolo indica que L2 no debe continuar",
        steps: [
          {
            id: "s1",
            title: "Transparencia",
            text: "Ya documenté el caso y el filtrado inicial. Para no hacerle perder tiempo, lo paso al equipo especialista según el protocolo de su cuenta.",
          },
          {
            id: "s2",
            title: "Expectativa",
            text: "El ticket [id] queda en el CRM. El tiempo de toma estimado es [SLA de la matriz]. Si desea, programo yo la devolución de llamada.",
            proactive: true,
          },
          {
            id: "s3",
            title: "Confirmación",
            text: "¿Hay algún horario en el que no pueda atender la devolución? Lo dejo anotado para el especialista.",
          },
        ],
      },
    ],
    protocols: [
      {
        id: "PRT-L2",
        name: "Protocolo L2 de filtrado y escalado",
        version: "1.0 plantilla",
        source: "plantilla",
        description:
          "Plantilla operativa de OpenCall. El cliente podrá sustituirla por su protocolo, destinos y SLAs cuando los facilite.",
        steps: [
          {
            id: "p1",
            title: "Identidad verificada",
            detail: "Nombre, empresa y dato de cuenta coinciden con la ficha CRM.",
            required: true,
          },
          {
            id: "p2",
            title: "Clasificación hecha",
            detail: "Consulta, incidencia, reclamación, acceso, facturación o producto, con prioridad.",
            required: true,
          },
          {
            id: "p3",
            title: "FAQ y manual consultados",
            detail: "Se buscó en la base de conocimiento y se aplicó el procedimiento L2 si existía.",
            required: true,
          },
          {
            id: "p4",
            title: "Intento de resolución documentado",
            detail: "Qué se probó, resultado y por qué no se cierra en este nivel.",
            required: true,
          },
          {
            id: "p5",
            title: "Usuario informado",
            detail: "Se explicó el siguiente paso, el destino y el tiempo estimado. Ofrecer callback.",
            required: true,
          },
        ],
        rules: [
          {
            id: "r1",
            when: "Caída de servicio, error 5xx persistente o impacto a varios usuarios",
            destination: "L3 · Plataforma",
            slaMinutes: 30,
          },
          {
            id: "r2",
            when: "Disputa de facturación no explicable con el desglose estándar",
            destination: "Finanzas",
            slaMinutes: 240,
          },
          {
            id: "r3",
            when: "Posible defecto de producto o integración CRM del cliente",
            destination: "Ingeniería / Integraciones",
            slaMinutes: 120,
          },
          {
            id: "r4",
            when: "Cuenta Enterprise con impacto en operación clínica o logística crítica",
            destination: "L3 · Cuenta dedicada",
            slaMinutes: 20,
          },
        ],
      },
    ],
    settings: {
      clientName: "Cliente demo (pendiente de onboarding)",
      lineNumber: "+57 601 555 0100 · línea en la nube (acceso pendiente)",
      telephony: {
        provider: "pendiente",
        status: "awaiting_client",
        inboundWebhook: "/api/telephony/inbound",
      },
      crm: {
        mode: "nativo",
        webhookUrl: "",
        apiEnabled: true,
      },
    },
    crmOutbox: [
      {
        id: "EVT-1",
        at: ago(1, 40),
        type: "ticket.escalated",
        target: "nativo",
        delivered: true,
        payload: {
          ticketId: "TKT-1042",
          destination: "L3 · Plataforma",
          customerId: "CUS-102",
        },
      },
    ],
  };
}
